const URL_BACKEND_BASE= 'http://localhost:8888';

const constants =  {
  URL_BACKEND_BASE,
  URL_BACKEND_LOGIN: `${URL_BACKEND_BASE}/login`,
  URL_BACKEND_PLAYLIST: `${URL_BACKEND_BASE}/playlist`,
  KEY_SONGBIRD_REFRESH_TOKEN: 'KEY_SONGBIRD_REFRESH_TOKEN',
  KEY_SONGBIRD_ACCESS_TOKEN: 'KEY_SONGBIRD_ACCESS_TOKEN',
};

export default constants;
