image: node:carbon
stages:
  - build
  - deploy

build songbird:
  stage: build
  cache:
    paths:
      - client/node_modules
  script:
    - cd client/
    - yarn
    - yarn build
  artifacts:
    - paths:
        - client/build/

pages:
  stage: deploy
  script:
    # Pages job only accepts a public/ folder at the root directory
    - mv client/build/ ../public/
  artifacts:
    paths:
      - public/
  only:
    - master
