image: node:carbon
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd client/
    - yarn
    - yarn build

pages:
  stage: deploy
  cache:
    paths:
      - client/node_modules
  script:
    # Pages job only accepts a public/ folder at the root directory
    - mv client/build/ ../public/
  artifacts:
    paths:
      - public/
  only:
    - master
