image: node:carbon
stages:
  - build-spotify-service
  - build-songbird
  - deploy

build spotify-service:
  stage: build-spotify-service
  cache:
    paths:
      - spotify-service/node_modules
  script:
    - cd spotify-service/
    - mkdir build
    - npm i
    - npm run build

build songbird:
  stage: build-songbird
  cache:
    paths:
      - client/node_modules
  script:
    - cd client/
    - npm i
    - npm run build
  artifacts:
    paths:
      - client/build/

pages:
  stage: deploy
  script:
    # Pages job only accepts a public/ folder at the root directory
    - mv client/build/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
