module.exports = {
  PLAYLIST_TYPE_TOP_SHORT_TERM: 'PLAYLIST_TYPE_TOP_SHORT_TERM',
  PLAYLIST_TYPE_TOP_MID_TERM: 'PLAYLIST_TYPE_TOP_MID_TERM',
  PLAYLIST_TYPE_TOP_LONG_TERM: 'PLAYLIST_TYPE_TOP_LONG_TERM',
  PLAYLIST_TYPE_POPULAR: 'PLAYLIST_TYPE_POPULAR',
};
