version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env

  postgres:
    image: postgres:9.6
    expose:
      - "5432"
    ports:
      - "5444:5432"
    # Due to a recent change this causes weird permission issues
    volumes:
      - ./postgres_volume/var/lib/postgresql/data:/var/lib/postgresql/data

  initdb:
    build:
      context: .
      dockerfile: initdb.Dockerfile

  manager:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env
    entrypoint:
      - node
    command:
      - ./playlist_manager/index.js
      - sync
