version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env

  postgres:
    image: postgres:9.6
    expose:
      - "5432"
    ports:
      - "5444:5432"
    volumes:
      - ./postgres_volume/var/lib/postgresql:/var/lib/postgresql

  manager:
    build:
      context: .
      dockerfile: server.Dockerfile
    # network_mode: host
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env
    entrypoint:
      - node
    # volumes:
      # - ./docker_logs/playlist_manager/logs/:/app/server/playlist_manager/logs/
    command:
      - ./playlist_manager/index.js
      - sync
