const express = require('express');
const jsonParser = require('body-parser').json();
const moment = require('moment');

const {
  getPlaylistTracks,
  createEmptyPlaylist,
  putPlaylistSongs,
  userHasPlaylist,
} = require('../services/spotify/playlistService.js');
const { getUserProfile } = require('../services/spotify/userService.js');
const { refreshAccessToken } = require('../lib/oauthClient.js');
const {
  addPlaylistSubscription,
  getUserByToken: getDbUserByToken,
  getSubscription,
} = require('../services/dbService.js');
const { PLAYLIST_METADATA } = require('../constants.global.js');
const { wrapRoute } = require('../lib/utils.js');

const router = express.Router();

async function createPlaylist(refreshToken, playlistType, _playlistOpts) {
  const { result: accessToken } = await refreshAccessToken(refreshToken);
  const { result: userProfile } = await getUserProfile(accessToken);
  const userId = userProfile.id;

  console.log(`Generating playlist ${playlistType} for ${userId}`);
  const playlistOpts = _playlistOpts || {
    name: PLAYLIST_METADATA[playlistType].title,
    description: 'Generated by Songbird',
  };
  const [{ result: tracks }, { result: playlistId }] = await Promise.all([
    getPlaylistTracks(accessToken, playlistType),
    createEmptyPlaylist(userId, accessToken, playlistOpts),
  ]);

  await putPlaylistSongs(userId, accessToken, playlistId, tracks);
  return { result: playlistId };
}

router.get(
  '/playlist',
  wrapRoute(async (req, res) => {
    const { refreshToken, playlistType } = req.query;
    if (![refreshToken, playlistType].every(e => !!e)) {
      return res
        .status(400)
        .json({ error: 'Bad request - missing query params!' });
    }
    const { result: accessToken } = await refreshAccessToken(refreshToken);

    const { result: userId } = await getUserProfile(accessToken);
    const userOpts = {
      userId,
      accessToken,
    };
    const { result } = await getPlaylistTracks(accessToken, playlistType);
    if (result.length === 0) {
      console.warn(`No tracks found for ${userId} with ${playlistType}`);
      return res.json({});
    }

    // Pluck tracks for response
    const tracks = result.map(track => ({
      name: track.name,
      album: track.album.name,
      artists: track.artists.map(artist => artist.name),
    }));
    return res.json({ tracks });
  })
);

router.post(
  '/playlist',
  jsonParser,
  wrapRoute(async (req, res) => {
    const { playlistType, refreshToken } = req.body;
    if (![playlistType, refreshToken].every(e => e)) {
      res.sendStatus(400);
      return;
    }

    await createPlaylist(refreshToken, playlistType);
    res.sendStatus(200);
  })
);

router.post(
  '/playlist/subscribe',
  jsonParser,
  wrapRoute(async (req, res) => {
    const { playlistType, refreshToken } = req.body;
    if (![playlistType, refreshToken].every(e => e)) {
      console.warn('Missing param in request body!');
      res.sendStatus(400);
      return;
    }

    const playlistOpts = {
      name: PLAYLIST_METADATA[playlistType].title,
      description: `Generated by Songbird | Last synced: ${moment().format(
        'LL'
      )}`,
    };
    const { result: dbUser } = await getDbUserByToken(refreshToken);
    if (!dbUser) {
      console.warn(`Could not find user with token: `, refreshToken);
      res.sendStatus(400);
      return;
    }

    const [
      { result: subscription },
      { result: accessToken },
    ] = await Promise.all([
      await getSubscription(dbUser.id, playlistType),
      await refreshAccessToken(refreshToken),
    ]);
    // Check if there is an existing subscription that is still valid (playlist not deleted)
    if (subscription) {
      const { result: hasPlayList } = await userHasPlaylist(
        accessToken,
        subscription.spotify_playlist_id
      );
      if (hasPlayList) {
        // Should be a mistake e.g. spamming button -  ignore request
        console.log(
          'Found existing playlist with id: ',
          subscription.spotify_playlist_id
        );
        res.sendStatus(400);
        return;
      }
    }

    console.log('Inserting subscription for user: ', dbUser.spotify_username);
    const { result: playlistId } = await createPlaylist(
      refreshToken,
      playlistType,
      playlistOpts
    );
    await addPlaylistSubscription(dbUser.id, playlistId, playlistType);
    res.sendStatus(200);
    // TODO better handle uncaught errors that already created playlists
  })
);

module.exports = router;
