version: '3'

services:
  api:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env

  postgres:
    image: postgres:9.6
    expose:
      - "5432"
    # so we can run psql stuff on 5433
    ports:
      - "5433:5432"

  manager:
    build: .
    env_file:
      - ./env/dev.env
      - /etc/songbird/secrets.env
    entrypoint:
      - node
    command:
      - ./playlist_manager/index.js
      - sync
