version: '3'

services:
  api:
    image: node:carbon
    ports:
      - "8888:8888"
    env_file:
      - /etc/songbird/secrets.env
    entrypoint:
      - yarn && yarn start

  postgres:
    image: postgres:9.6
    expose:
      - "5432"
