version: '3'

services:
  api:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - /etc/songbird/secrets.env

  postgres:
    image: postgres:9.6
    expose:
      - "5432"
  manager:
    image: node:carbon
    env_file:
      - /etc/songbird/secrets.env
    working_dir:
      - ./playlist_manager/
    entrypoint:
      - node
    command:
      - index.js
